import {v4 as uuid} from "uuid";
import * as dayjs from 'dayjs'
import MapStore from "../lib/mapstore";
import BlogPost from "../src/Classes/BlogPost"
/* BlogPost {
* id: string (autogenerated)
* title: string optional
* body: string
* author: string optional
* created_on: Date
* last_edited: Date
* comments: Comment[]
* */

const BLOG_POSTS = new Map();
const mapStore = new MapStore("blog-posts.json");

mapStore.read()
    .then(
        (blogPosts) => {
            for (let [id, blogPost] of blogPosts) {
                BLOG_POSTS.set(id, blogPost);
            }
        },
        (err) => {
            console.error(err);
        }
    );

export const getBlogPost = (sort) => {
    const blogPosts = Array.from(BLOG_POSTS.values());
    blogPosts.sort((a, b) => {
        if (sort === "asc") {
            return a.lastEdited - b.lastEdited;
        } else {
            return b.lastEdited - a.lastEdited;
        }
    });
    return blogPosts;
}


export async function createBlogPost({ title, body, author}) {
    const id = uuid();
    const lastEdited = Date.now();
    const created_on = Date.now();
    const empty_comment = [];
    const blog_post = {
        id,
        title,
        body,
        author,
        created_on,
        lastEdited,
        empty_comment
    };
    BLOG_POSTS.set(id, blog_post);
    await mapStore.save(BLOG_POSTS);
    return blog_post;
}

